"""Inicialización de la base de datos

Revision ID: 8dfdc0b10a45
Revises: 
Create Date: 2024-05-30 11:42:35.575998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfdc0b10a45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('apellido', sa.String(length=50), nullable=True),
    sa.Column('usuario', sa.String(length=50), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=10), nullable=True),
    sa.Column('contrasenia', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('correo'),
    sa.UniqueConstraint('correo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cliente')
    # ### end Alembic commands ###
